### ISSUE TITLE
undefined function Lazer\Classes\mb_check_encoding()

### ISSUE THREAD

**Issue by anasybal** [Lazer-Database/Lazer-Database#67]
hey i'm trying to use your library and i got this error any idea how to solve it?

```bash
your name : anas
PHP Fatal error:  Uncaught Error: Call to undefined function Lazer\Classes\mb_check_encoding() in /home/laganty/tools/php/bot-lazer-storage/vendor/greg0/lazer-database/src/Classes/Database.php:218
Stack trace:
#0 /home/laganty/tools/php/bot-lazer-storage/vendor/greg0/lazer-database/src/Classes/Database.php(186): Lazer\Classes\Database->setField()
#1 /home/laganty/tools/php/bot-lazer-storage/index.php(23): Lazer\Classes\Database->set()
#2 {main}
  thrown in /home/laganty/tools/php/bot-lazer-storage/vendor/greg0/lazer-database/src/Classes/Database.php on line 218
  ```

the code :

```php
$txt = readline("your name : ");
$row = Lazer::table('test');
   $row->set(array(
      'id' => 1,
      'nickname' => $txt
   ));
   $row->save();
```

**Comment by anant-svc** [comment]
@laganty check whether mbstring module is installed for the php version and if not then install it.

**Comment by anant-svc** [comment]
@laganty You can request any feature so it will be added with new release.
